modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dmnr"
version="3.1.9"
displayName="Dragon Magic and Relics"
credits="Thanks to jsementj for the amazing armor model and texture! Thanks to Mithion for helping creating some code elements of this mod! Also thanks to Ceddi and Nico for helping with testing and balancing."
authors="Joh0210"
logoFile="dmnr.png"
description='''
A mod to expand your magic to compete with gods!
'''


[[dependencies.dmnr]]
   modId="forge"
   mandatory=true
   versionRange="[47.1,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.dmnr]]
   modId="mna"
   mandatory=true
   versionRange="[3.0.0.14,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.dmnr]]
   modId="curios"
   mandatory=true
   versionRange="[5.4.7,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.dmnr]]
   modId="caelus"
   mandatory=true
   versionRange="[3.1.0,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.dmnr]]
   modId="geckolib"
   mandatory=true
   versionRange="[4.2.2,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.dmnr]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1]"
   ordering="NONE"
   side="BOTH"